=== HaraldSimon/x2xmldatabinding/Tests/XSD/DataBindingResult.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp1 (http://www.altova.com) by M. van Renswoude (XÂ²Software) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataBindingResult">
		<xs:annotation>
			<xs:documentation>Defines the expected intermediate result of a Data Binding</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Schemas">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Schema" type="Schema" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Schema">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Items">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Item" type="Item" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Item">
		<xs:sequence>
			<xs:element ref="ItemType"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:choice>
				<xs:element name="Interface">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="InterfaceType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Collection">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ItemName" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Enumeration">
					<xs:complexType>
						<xs:sequence/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ItemType">
		<xs:simpleType>
			<xs:restriction base="xs:NMTOKENS">
				<xs:enumeration value="Interface"/>
				<xs:enumeration value="Collection"/>
				<xs:enumeration value="Enumeration"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="InterfaceType">
		<xs:simpleType>
			<xs:restriction base="xs:NMTOKEN">
				<xs:enumeration value="Interface"/>
				<xs:enumeration value="ComplexType"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== HaraldSimon/x2xmldatabinding/Tests/Data/02. Collection_expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataBindingResult xsi:noNamespaceSchemaLocation="F:\Archive\2007\XMLDataBinding\Tests\XSD\DataBindingResult.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Schemas>
		<Schema>
			<Name>02. Collection</Name>
			<Items>
				<Item>
					<Name>Root</Name>
					<ItemType>Interface</ItemType>
					<Interface>
						<InterfaceType>Interface</InterfaceType>
					</Interface>
				</Item>

        <!-- TODO: Parts moet worden gecollapsed naar een ItemType Collection -->
				<Item>
					<Name>ComplexParts</Name>
					<ItemType>Interface</ItemType>
					<Interface>
						<InterfaceType>Interface</InterfaceType>
					</Interface>
				</Item>

				<Item>
					<ItemType>Collection</ItemType>
					<Name>ComplexPartList</Name>
          <Collection>
            <ItemName>ComplexPart</ItemName>
          </Collection>
				</Item>

				<Item>
					<Name>ComplexPart</Name>
					<ItemType>Interface</ItemType>
					<Interface>
						<InterfaceType>Interface</InterfaceType>
					</Interface>
				</Item>


        <Item>
          <Name>SimpleParts</Name>
          <ItemType>Interface</ItemType>
          <Interface>
            <InterfaceType>Interface</InterfaceType>
          </Interface>
        </Item>

				<Item>
					<ItemType>Collection</ItemType>
					<Name>SimpleValueList</Name>
          <Collection>
            <ItemName>SimpleValue</ItemName>
          </Collection>
				</Item>
      </Items>
		</Schema>
	</Schemas>
</DataBindingResult>

=== HaraldSimon/x2xmldatabinding/Tests/Data/01. Basic simple and complex types_expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataBindingResult xsi:noNamespaceSchemaLocation="F:\Archive\2007\XMLDataBinding\Tests\XSD\DataBindingResult.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Schemas>
		<Schema>
			<Name>01. Basic simple and complex types</Name>
			<Items>
				<Item>
					<ItemType>Interface</ItemType>
					<Name>TestElement</Name>
					<Interface>
						<InterfaceType>Interface</InterfaceType>
					</Interface>
				</Item>
				<Item>
					<ItemType>Interface</ItemType>
					<Name>TestComplexType</Name>
					<Interface>
						<InterfaceType>ComplexType</InterfaceType>
					</Interface>
				</Item>
			</Items>
		</Schema>
	</Schemas>
</DataBindingResult>
